version: '3.7'

# starts 4 docker containers running minio server instances. 
# nginx is used as load balancer and exposes the service via port 9000
services:
  minio1:
    image: minio/minio:RELEASE.2019-08-14T20-37-41Z
    volumes:
      - data11:/data1
      - data12:/data2
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data1 http://minio1/data2 http://minio2/data1 http://minio2/data2 http://minio3/data1 http://minio3/data2 http://minio4/data1 http://minio4/data2 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio1:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m

  minio2:
    image: minio/minio:RELEASE.2019-08-14T20-37-41Z
    volumes:
      - data21:/data1
      - data22:/data2
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data1 http://minio1/data2 http://minio2/data1 http://minio2/data2 http://minio3/data1 http://minio3/data2 http://minio4/data1 http://minio4/data2 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio2:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m

  minio3:
    image: minio/minio:RELEASE.2019-08-14T20-37-41Z
    volumes:
      - data31:/data1
      - data32:/data2
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data1 http://minio1/data2 http://minio2/data1 http://minio2/data2 http://minio3/data1 http://minio3/data2 http://minio4/data1 http://minio4/data2 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio3:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m

  minio4:
    image: minio/minio:RELEASE.2019-08-14T20-37-41Z
    volumes:
      - data41:/data1
      - data42:/data2
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data1 http://minio1/data2 http://minio2/data1 http://minio2/data2 http://minio3/data1 http://minio3/data2 http://minio4/data1 http://minio4/data2 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio4:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-conf.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    ports:
      - "9000:9000"

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data11:
  data12:
  data21:
  data22:
  data31:
  data32:
  data41:
  data42:

